### ISSUE TITLE
jquery - dependency was not found ???

### ISSUE THREAD

**Issue by sldobri** [shakee93/vue-toasted#1]
This dependency was not found:

* jquery in ./~/velocity-animate/velocity.js

Velocity is an animation engine with the same API as jQuery's $.animate(). It works with and without jQuery.

Download Velocity, include it on your page, and replace all instances of jQuery's $.animate() with $.velocity().

**Comment by shakee93** [comment]
this plugin doesn't depend on jQuery but it depends on Velocity and hammerjs. velocity is pre included in the build so you will not need to include it in your project.

Will you be able to reproduce this ? so i can take a look.

thanks

**Comment by sldobri** [comment]
I create new project and work perfect.

plz close this issue.

great job!!!
