### ISSUE TITLE
can not set global options if I use script tag for vue.

### ISSUE THREAD

**Issue by lili21** [shakee93/vue-toasted#10]
```
// register plugin if it is used via cdn or directly as a script tag
if (typeof window !== 'undefined' && window.Vue) {
    window.Vue.use(Toasted);
}
```

> Vue.use automatically prevents you from using the same plugin more than once, so calling it multiple times on the same plugin will install the plugin only once.

so I can not set global options by `Vue.use(Toasted, options)`.

**Comment by shakee93** [comment]
Thank you for the feedback. the above code block you have mentioned is used to allow people to use the plugin directly via cdn or script tag. i have tested, the problem only resists when we use the plugin via script tags.

```Javascript
// register plugin if it is used via cdn or directly as a script tag
if (typeof window !== 'undefined' && window.Vue) {
    window.Toasted = Toasted;
}
```
and then you can register the plugin as you would do normally.

```javascript
Vue.use(Toasted, yourOptions);
```

please let me know if you have a better solution. thanks
