### ISSUE TITLE
not support ie9 when used in nuxt

### ISSUE THREAD

**Issue by muzi131313** [shakee93/vue-toasted#101]
in ie9 browser, console panel report that: `Float32Array was undefined`
![image](https://user-images.githubusercontent.com/2398149/50753874-82c33d00-128e-11e9-8033-9200e2a46479.png)
there was a [Float32Array  polyfill](https://github.com/inexorabletash/polyfill/blob/master/typedarray.js#L934)

**Comment by shakee93** [comment]
IE 9 Not Supported ! Mentioned in the readme.
