### ISSUE TITLE
Demo does not work

### ISSUE THREAD

**Issue by dacoders77** [shakee93/vue-toasted#104]
![image](https://user-images.githubusercontent.com/36567186/51165119-2ef7bb80-186d-11e9-9d01-bac1286840c5.png)

**Comment by seekcx** [comment]
+1

**Comment by shakee93** [comment]
are you seeing any console errors ? i can view the demo without any issues

**Comment by seekcx** [comment]
@shakee93 

![image](https://user-images.githubusercontent.com/8244814/51506980-9d1e1e80-1e29-11e9-807a-894db80d3b0a.png)
