### ISSUE TITLE
Multiple icon classes using fontawesome

### ISSUE THREAD

**Issue by EdwinvanDessel** [shakee93/vue-toasted#108]
Hi,

Verry happy withvue-toasted. Everything works like a charm except for the icon in my globally registered toast. I have copied/created this global toast for my application:

```
Vue.toasted.register('infotoast',
  (payload) => {
    return payload.message;
  },
  {
    type: 'info',
    className: 'info-toast',
    iconPack: 'fontawesome',
    icon: {
      name: 'fal fa-info-square'
    },
    duration: 3000
  }
);
```

But when I execute this code I get the following error message in the console:
`Uncaught (in promise) DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided ('fal fa-exclamation-triangle') contains HTML space characters, which are not valid in tokens.`

Apparently the space between fal and fa-exclamation-triangle is not allowed, but without fal the icon is not loaded.

Any suggestions?

Thanks,
Edwin

**Comment by KarmaCop213** [comment]
I've a similar problem. 
I can't see any exceptions, but the toaster isn't shown and the code after I create the toaster isn't run.
What kind of sorcery do I need to do to use font awesome icons?

**Comment by KarmaCop213** [comment]
Thank you!
My problem was that I was using in the icon property "fa fa-times", removed "fa" from there and everything is now working as it should.

**Comment by shakee93** [comment]
Great !!
