### ISSUE TITLE
Overwrite default animations

### ISSUE THREAD

**Issue by andriy-f** [shakee93/vue-toasted#109]
Hi,

Is it possible to override animations with custom ones?
Currently animations are set via style attribute and can't be overriden (like translateY(-35px);) by css classes. AFAIK you use anime.js. How to override animations?

What if I need to do slide from left?

**Comment by shakee93** [comment]
the animations are made with anime.js. we would not be able to animate with css classes. but we can setup a way to override the animations.

take a look at the animations 
https://github.com/shakee93/vue-toasted/blob/master/src/js/animations.js

**Comment by andriy-f** [comment]
@shakee93 Thanks

**Comment by muscle-rhnkyr** [comment]
Or disable animation ?

**Comment by shakee93** [comment]
PR welcome for this !

**Comment by MokkaKowalewska** [comment]
Hi Guys, have You achieved overriding default animations?
