### ISSUE TITLE
Used in nuxt.js when the error.

### ISSUE THREAD

**Issue by Abel94** [shakee93/vue-toasted#11]
![qq 20170413161003](https://cloud.githubusercontent.com/assets/8244814/24998500/e440036c-206c-11e7-9c55-b39d4a021627.png)

**Comment by shakee93** [comment]
I haven't used nuxt.js can you please elaborate. when and how this is caused ?

**Comment by Abel94** [comment]
I think it should be nuxt.js rendering in the server caused by the server rendering no `document`.

**Comment by shakee93** [comment]
Yeah i think you should exclude `vue-toasted` from server rendering. add it only on client side.
