### ISSUE TITLE
It is too big for nomal user

### ISSUE THREAD

**Issue by machengda89** [shakee93/vue-toasted#111]
![image](https://user-images.githubusercontent.com/6835957/53676505-38829900-3cde-11e9-9949-916d5865e428.png)

Can we split the css file，just import what we want，like cent-top css。Make this lib much more light

**Comment by shakee93** [comment]
yes it is possible. you can import the index-core.js file into your project.

https://github.com/shakee93/vue-toasted/blob/d9ac39c60698c7cc7120b1164dde70f1b44c2101/src/index-core.js#L1
