### ISSUE TITLE
Upgrade to 1.1.26 removes background-color from toast in primary theme

### ISSUE THREAD

**Issue by ICATT** [shakee93/vue-toasted#112]
Upgrading to version 1.1.26 (from 1.1.24 in our case), seems to remove background-colors from toasts when using the old primary theme.

Removing the space between .toasted and .primary in the CSS selector below fixes the issue.

.toasted .primary, .toasted.toasted-primary

Changing the theme from primary to toasted-primary also works as a temporary fix.

**Comment by fureszk** [comment]
I experience the same issue. Thank you for posting the solution!

**Comment by shakee93** [comment]
this is due to the older css. it is updated in the latest version

**Comment by dyllandry** [comment]
I'm getting this problem on 1.1.27.
Changing theme from `primary` to `toasted-primary` alleviated the problem. 
```
"dependencies": {
    ...
    "vue-toasted": "^1.1.24",
    ...
}
```
```
$ npm list --depth=0 | grep vue-toasted
├── vue-toasted@1.1.27
```
