### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by MrCapsLock** [shakee93/vue-toasted#120]
Hello, I'm using nuxt/toast that developed base on vue-toasted. also i'm using vue-toasted in another project with vue. I'm using Persian language so i need rtl in toast messages. but i can't find any option or something else to support rtl.
Is it available to use?
Thanks

**Comment by Nfinished** [comment]
Could this be solved with styling?

**Comment by MrSpecterist** [comment]
I did like this .toasted{border-radius:0; direction: rtl} in css file of toasted project but it's not effected. also I tried with className but it does not work (maybe i was used it wrong), and I don't know is another way for that or not!

**Comment by Nfinished** [comment]
Seems to be working. https://jsfiddle.net/2r6x4g0L/

**Comment by MrCapsLock** [comment]
sorry for my delay. seems it's okay. But is not it better to make an option for it?

**Comment by shakee93** [comment]
This can be achieved with styling. PR welcome to integrate it in the package.

Thanks.
