### ISSUE TITLE
Wrong font family

### ISSUE THREAD

**Issue by joni1802** [shakee93/vue-toasted#121]
Hello,

my Toast is using the default browser font and not the roboto font. I am using this plugin in combination with vuetify. Did anyone have the same problem?

**Comment by joni1802** [comment]
My fault. I did not see that vuetify is the problem. It sets the font-family only to the application class not the entire body by default.

**Comment by StephanKroukamp** [comment]
> My fault. I did not see that vuetify is the problem. It sets the font-family only to the application class not the entire body by default.

Can you please share how you did this? im experiencing the same thing.

**Comment by betoflakes** [comment]
How did you fix it?

**Comment by joni1802** [comment]
I have simply added the necessary css inside the head in the index.html.
```html
<style>
  .toasted {
    font-family: 'Roboto', sans-serif;
    font-weight: 300;
  }
</style>
```
