### ISSUE TITLE
fail to set option singleton by `this.$toasted.show(text, {singleton: true})` 

### ISSUE THREAD

**Issue by clevergod** [shakee93/vue-toasted#126]
version:  "1.1.26"

`this.$toasted.show(text, {singleton: true})` doesn't work
`
import Toasted from 'vue-toasted'
Vue.use(Toasted, {singleton: true}) is work
`

**Comment by shakee93** [comment]
it is intended to work that way. singleton should be added on init.

**Comment by V-kto** [comment]
Too bad !
It could be useful to be able overriding the singleton option...
