### ISSUE TITLE
No style...

### ISSUE THREAD

**Issue by tonsV2** [shakee93/vue-toasted#13]
The code below renders the toast without the border. Should I include some css or something?

        this.$toasted.show('Posted!', {
          theme: 'outlined',
          position: 'top-right',
          duration: 2000
        })

**Comment by shakee93** [comment]
it is `outline`. it should look like below...

```javascript
this.$toasted.show('Posted!', {
      theme: 'outline',
      position: 'top-right',
      duration: 2000
})
```

**Comment by tonsV2** [comment]
My bad, thanks!
