### ISSUE TITLE
Issue with appending container to body

### ISSUE THREAD

**Issue by TomaszBernat96** [shakee93/vue-toasted#131]
I think that there is some problem with commit 3cb3cbb098d4b4b545a23646ce2533c816f27ac5 (merged 3 days ago which in case of issue #115 ). This is due to the following error which occures in console when `vue-toasted` should be append to body. 

Image with content of error in console:
![image](https://user-images.githubusercontent.com/26420483/58004141-d10d0600-7ae2-11e9-94b2-7263520c7e83.png)

It makes following syntax not working:
`this.$toasted...`

This syntax is still working:
`Vue.toasted...`

**Comment by shakee93** [comment]
i have tested this in my local environment. it is not throwing any error. maybe you could setup a fiddle ? it would be much helpful.

btw toast container creation is moved to toasts.js
https://github.com/shakee93/vue-toasted/commit/3cb3cbb098d4b4b545a23646ce2533c816f27ac5#diff-88f2a67e2fa67b317a5b828283495596

**Comment by TomaszBernat96** [comment]
To be more specific i use this in my dajngo app. I used `Direct Usage` method from Installation chapter. This error occurs when i'm calling `Vue.use(Toasted)` in my base script. Every js file where i have my components inherits from this file.

This error started 3 days ago when master branch was updated with merge. Before merge everything worked fine that's why i'm assuming there must be a relation between changes in merged commits and this error. 

I think that there is no point in setting fiddle for this because it gives me error when it should be mounted to body element. It is one of the very first things which are executed in my app. 

@shakee93 what method of installation have u used ?

**Comment by tabishiqbal** [comment]
Having the same issue

**Comment by awebartisan** [comment]
I am having the same problem... has anybody figured out on how to solve this??

**Comment by charles-owen** [comment]
Add Toasted after the document is initialized. I have a simple Ready function like this:

/**
 * Call a function when the document is ready.
 * @param fn Function to be called on document ready
 */
Ready.go = function(fn) {
    if (document.attachEvent ? document.readyState === "complete" : document.readyState !== "loading"){
        fn();
    } else {
        document.addEventListener('DOMContentLoaded', fn);
    }
}

And I load Toasted this way:
		Ready.go(() => {
			// Toasted tries to add to the document body when it is initialized,
			// so it has be be loaded after the document is ready.
			Vue.use(Toasted);
                }

**Comment by shakee93** [comment]
make sure `body` element is available in the dom.
