### ISSUE TITLE
Argument of type 'ToastObject' is not assignable to parameter of type '(value: any) => any'.

### ISSUE THREAD

**Issue by darthf1** [shakee93/vue-toasted#138]
Hi!

Using Toast with Nuxt (and the corresponding [module](https://github.com/nuxt-community/modules/tree/master/packages/toast)) and Typescript, I've got the following code:

```
this.$toast.success('ok')
```
This gives me the following message in PHPStorm:
```
Error:(196, 81) TS2345: Argument of type 'ToastObject' is not assignable to parameter of type '(value: any) => any'.
  Type 'ToastObject' provides no match for the signature '(value: any): any'.
```

Got any idea?

**Comment by Hakall** [comment]
Same things for other ToastOptions properties:
`Types of property 'position'`
`Types of property 'duration'`
