### ISSUE TITLE
minified/production jQuery undefined error.

### ISSUE THREAD

**Issue by azhard4int** [shakee93/vue-toasted#14]
Hi,

We are using jQuery 3.1.1 and getting `"Uncaught TypeError: Cannot read property 'jQuery311050336921825352572' of undefined"` when running gulp mode in production.

Can you kindly look into this.

Thanks

**Comment by azhard4int** [comment]
Just to give an update, the issue relies in the vue-toasted.min.js file, I have compiled the files through the src folder and everything is working fine now.

**Comment by shakee93** [comment]
please provide a way to reproduce this. so i can take a look.

**Comment by shakee93** [comment]
Closing as the thread is inactive
