### ISSUE TITLE
Full width option

### ISSUE THREAD

**Issue by nilsi** [shakee93/vue-toasted#15]
Really like this plugin! Great Job!

I would like to have a full width option where the notification is aligned at the top. Is this possible?

**Comment by shakee93** [comment]
it is possible ill add it to my list..

**Comment by ryanisenia** [comment]
HI Shakee,

It's very easy to use plugin. Now i am looking for the full-width option?
is the full-width feature available? Please let us know.

Thanks,
Ritesh

**Comment by shakee93** [comment]
Sorry i missed this message. it is not available yet. ill update this issue once it is available.

thanks

**Comment by shakee93** [comment]
full width option added shakee93/vue-toasted@cb80fba
