### ISSUE TITLE
Don't work with this.$router.go()

### ISSUE THREAD

**Issue by alexPouivet** [shakee93/vue-toasted#154]
Hi,

I use vue-toasted in my Nuxtjs project and I try tu use vue-toasted to show succeed messages for my users. For the delete case I need to reload the page after the delete success, so I use `this.$router.go()` to do it but it don't work when I try to add vue-toasted  like that : 
![error-vue-toasted](https://user-images.githubusercontent.com/35558793/76219734-92357180-6216-11ea-9755-08a7b58c888a.png)

is it just not the good implementation or it's not possible to use it ?

I know I can use `this.$router.push()` but it don't work for reload pages, I already try.
Thank you

**Comment by alexPouivet** [comment]
I found the solution, it was just the good way to use it, this is the good  :
![vue-toasted](https://user-images.githubusercontent.com/35558793/76221879-0cb3c080-621a-11ea-98e8-4b42946ce34a.png)

**Comment by shakee93** [comment]
you can add the `$toasted` call after the `$router.go`. or in the path component `mounted`
