### ISSUE TITLE
Feature Request: Adjust Offset

### ISSUE THREAD

**Issue by SaMiCoOo** [shakee93/vue-toasted#16]
Great Work !!!

Hopefully you can add a way to adjust the offset, or at least an option for no offset at all to make it work both as a toast and snackbar.

**Comment by shakee93** [comment]
Sorry for the delayed response. you can use css to adjust the offset. set the position to 'top-center'

```css
#toasted-container .toasted {
    top: 0px;
}
```

this will change the offset. you can also add a custom classname and use that. hope that helps.

ill see if i can add the snackbar feature with action 😉
