### ISSUE TITLE
Documentation is extremely poor

### ISSUE THREAD

**Issue by lliendo** [shakee93/vue-toasted#163]
Please document clearly what you component is capable/not capable of doing. I had to basically find this issue to understand that you can pass arbitrary HTML as part of the message when displaying a notification: [support router-link in toasts](https://github.com/shakee93/vue-toasted/issues/18). The overall documentation is extremely poor and unorganized. Please take the time to add quality documentation (and diverse examples showing different use cases) so users don't need to dig in the code or issues to understand how your component is supposed to be used.

**Comment by shakee93** [comment]
Hey @lliendo Sorry for getting you in trouble. first of all this package is not a component. it is a service.

https://github.com/shakee93/vue-toasted#methods
you can see it clearly says string or html

and also you can use `$router.push` via action which does the same. take a look at the doc with example here
https://github.com/shakee93/vue-toasted#actions--fire
