### ISSUE TITLE
Vue3 Support

### ISSUE THREAD

**Issue by alvarosaburido** [shakee93/vue-toasted#179]
Hi, first of all, an amazing library.

Are there plans to update the library for Vue3 use?

Kind Regards

**Comment by shakee93** [comment]
closing as merged

**Comment by eino** [comment]
Hi,
thank you both for your work on this library!
I was trying to use this next branch in my Vue3+TS project,
however when after installing with 
```
import VueToasted from 'vue-toasted';
createApp(App)
    .use(VueToasted)
```
the project compiles just fine, but on run I get this error

Uncaught TypeError: t.prototype is undefined
    install vue-toasted.min.js:1
    use runtime-core.esm-bundler.js:3132
    ts main.ts:27
    Webpack 7

Would you have any idea where to go from here?

Kind regards,
