### ISSUE TITLE
How to use without npm or nodejs.

### ISSUE THREAD

**Issue by d0u9** [shakee93/vue-toasted#21]
I have a light web app which contains just one html and few css and js files. I don't want to install npm, because it is not necessary.

So, How could I use this beautiful lib with out npm? I want it to act as Jquery or vue, which just include a few of js and css files, no npm, no nodejs.

**Comment by shakee93** [comment]
You can use the direct link as used in the demo.

https://unpkg.com/vue-toasted

**Comment by shakee93** [comment]
add the direct script after the vue script.

`Vue.use(Toasted)`

viola !! thats it !!
