### ISSUE TITLE
Mobile toasts not appearing at bottom

### ISSUE THREAD

**Issue by gmask** [shakee93/vue-toasted#26]
I know from reading the issues here and testing the demo site that the toasts are supposed to appear full width at the bottom of the page while on mobile. However on my site the config position is retained regardless of device or screen width.

My site is using Bootstrap 4. How can I get this behavior?

**Comment by shakee93** [comment]
Please update to the latest version. provide reproduce it so i can take a look. it is working as expected on the demo.

the toast has to be in full width at bottom of the page

**Comment by shakee93** [comment]
There was a bug in mobile full width. fixed it in the latest release. check if it is related to this issue. thanks

**Comment by gmask** [comment]
Confirmed fixed in latest release. Thanks!
