### ISSUE TITLE
Babelify vue toasted ?

### ISSUE THREAD

**Issue by ouraios** [shakee93/vue-toasted#27]
Hello,
I'm using this component in my vueJs project, but apparently there are Object.assign method which are not polyfilled in your min.js.
Is it possible to babelify it ?

**Comment by shakee93** [comment]
Does it throw an error ? i haven't included a polyfill to it as it is developed upon ES6. it seems it needs a polyfill to run on the old browsers.

**Comment by ouraios** [comment]
IE doesnt support Object.assign method at all
You should use babel library to be sure that your component will support ES5 too

**Comment by shakee93** [comment]
@ouraios Thank you. Object.assign polyfill added on the latest version.

**Comment by ouraios** [comment]
@shakee93 no problem ! You should say that your component support IE10+ in your readme, this is a big positive "feature" ;)

**Comment by shakee93** [comment]
Thanks will add that. 😄
