### ISSUE TITLE
Not worked in QQBrowser and UCBrowser for Android

### ISSUE THREAD

**Issue by hanzhenlong** [shakee93/vue-toasted#28]
the component is cool, but it doesn't work in QQBrowser and UCBrowser for Android.  It worked normally in mobile chrome browser.

**Comment by ouraios** [comment]
I think this is related to my issue #27 
Those browsers dont support ES6

**Comment by shakee93** [comment]
Related to #27 Fixed with 702a81497138d03eff631d07b12f1db785d0769c
