### ISSUE TITLE
Move Velocity and Hammerjs from the dev deps to the deps

### ISSUE THREAD

**Issue by adinvadim** [shakee93/vue-toasted#29]
Because on the first look the empty deps mean that the library doesnt have a deps

**Comment by adinvadim** [comment]
https://github.com/shakee93/vue-toasted/pull/30

**Comment by shakee93** [comment]
It was already there on the earlier releases. i have removed it as it will be installed with the package which the plugin doesn't need as the plugins start point is the min file.
