### ISSUE TITLE
Nuxt.js <3 Toasted

### ISSUE THREAD

**Issue by pi0** [shakee93/vue-toasted#31]
Hi! Just wanted to inform you we have updated [@nuxtjs/toast](https://github.com/nuxt-community/modules/tree/master/modules/toast) module to 2.0.0 using toasted. This module helps users quickly adding `vue-toasted` to their Nuxt project. Would be awesome if you can add a link to module in official README.

Thanks.

**Comment by shakee93** [comment]
Thank you 💓 Its a pleasure !! ill add that to readme !!!
