### ISSUE TITLE
Clear toasts when route changes

### ISSUE THREAD

**Issue by sergiocastrovale** [shakee93/vue-toasted#33]
I don't know if this is already possible or it's a possible future feature but it would be very useful to be able to clear all toasts when the page changes.

Let's say you are showing a success message in a form and you have a call to action to "proceed" ... The message will stay there indefinitely unless you manually trigger something that clears it.

It would be awesome if we could somehow bind it to route changes.

**Comment by shakee93** [comment]
by the way. when you use `push` on the action. it will automatically close that toast but not all toasts.

once we have the all clear option we can definitely hook it to the route. please follow #32 i am closing this as a duplicate
