### ISSUE TITLE
Only one toast at a time

### ISSUE THREAD

**Issue by sergiocastrovale** [shakee93/vue-toasted#37]
Is there a way to globally prevent that no more than a single toast is shown simultaneously? I'm trying to prevent this from happening:

![screenshot_1](https://user-images.githubusercontent.com/8822036/31014866-02e8be08-a515-11e7-813f-98f9adb1fce4.png)

I know I could just use the recently-added clear method but it seems a bit too overwhelming to have to make that call each time I trigger a toast. I was wondering if I could clear all toasts as soon as a new one is shown.

**Comment by shakee93** [comment]
it will be available in the upcoming build. `singleton : true` or something..

**Comment by sergiocastrovale** [comment]
That's awesome. Maybe `unique: true`?

Any idea on when it will be available? Thanks for the great package and fast support.

**Comment by shakee93** [comment]
i think `singleton` gives the idea of the options than `unique`. maybe in couple of hours 🚀 cheers !!

**Comment by lsc949982212** [comment]
the bug is exist still on version 1.1.24,  how to resolve?

**Comment by ZtheLeader** [comment]
`singleton: true` is not working as action.

**Comment by mpalencia** [comment]
singleton: true --> still not working on 1.1.27
any idea on how to implement this?

**Comment by FilArt** [comment]
> singleton: true --> still not working on 1.1.27
> any idea on how to implement this?

you can use `this.$toasted.clear()` to kill old notys
