### ISSUE TITLE
[Request] Bower package

### ISSUE THREAD

**Issue by paulogdm** [shakee93/vue-toasted#40]
Hello! Can you please consider adding this repo to bower?

Best

**Comment by shakee93** [comment]
Sorry for the delayed response, i have been so busy lately,

you can easily install a git repo as a bower component

```shell
bower install https://github.com/shakee93/vue-toasted.git
```

this will install the latest version of the package. if you need install a specific version
check the versions here : https://github.com/shakee93/vue-toasted/releases

```shell
bower install https://github.com/shakee93/vue-toasted.git#v1.1.20
```

Hope that helps

**Comment by paulogdm** [comment]
Omg, sorry, never thought of this option.
Anyway, vue-toasted is now availableat cdnjs >> https://github.com/cdnjs/cdnjs/issues/12017
Ty for this repo!

**Comment by shakee93** [comment]
Thanks buddy 🤞
