### ISSUE TITLE
typeof returns 'object' instead of 'array' in createAction

### ISSUE THREAD

**Issue by ryanmr-daugherty** [shakee93/vue-toasted#41]
This `action.class` option is undocumented as far as I can tell, but it is a valuable feature for adding selectors for test automation.

In the createAction function, there is a switch on `typeof action.class` that then expects either a string or array, but `typeof` only [returns `object` for arrays](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof). Using a string as a fallback works, but fixing this would require additional logic to check if the object is an array.

https://github.com/shakee93/vue-toasted/blob/c9bba80cb05b8208134b9a686f9ce57885702071/src/js/show.js#L234

**Comment by shakee93** [comment]
Thank you, this will be fixed in the upcoming commit. and will be documented.
