### ISSUE TITLE
Font Awesome 5

### ISSUE THREAD

**Issue by luaz** [shakee93/vue-toasted#42]
Any plan to support Font Awesome 5 icon?

I manage to hack up a solution, but it would be great to have official support for it.

Use the following code to load Font Awesome 5 Icon with vue-toasted.
```
import fontawesome from '@fortawesome/fontawesome'
import faSolid from '@fortawesome/fontawesome-free-solid'

Vue.toasted.show(`${fontawesome.icon(faSolid.faCoffee).html} Hello`, {
  type: 'success',
  duration: 3000
})
```
For spacing and margin, include the following css.
```
.toasted-container .toasted > svg {
  margin-right: .5rem;
  margin-left: -.4rem;
}
```

https://code.luasoftware.com/tutorials/vuejs/vue-toasted-with-font-awesome-icon/

**Comment by shakee93** [comment]
Hey bud sorry for the delayed response, being busy lately.. i might be looking into adding fontawesome support in the future.

if you have a more appropriate way of adding support to this, may be a pull request.

**Comment by paulogdm** [comment]
+1

**Comment by shakee93** [comment]
Added support to fontawesome.

simply set the icon pack to `fontawesome` !!

```javascript
Vue.use(VueToasted, {
    iconPack : 'fontawesome'
});
```

**Comment by ronny332** [comment]
Hi,
imho the author meant the support for FA5 in a different kind of way.

As you can see in the opening post, the FA5 lib returns a finally usable object, which can be inserted directly.
There will be no further load request from CSS or anything else. The has a big advantage over the CSS way, because you just have to include the icons, you are really using.

**Comment by grofit** [comment]
Any progress on this as I am using FA5 and could do with hooking those icons into the toasts

**Comment by twarlop** [comment]
in case you are still wondering (i'm assuming this is your intent):

```
import { library, dom } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
import { faExclamation } from '@fortawesome/free-solid-svg-icons';
import VueToasted from 'vue-toasted';

// add any icon you use manually
library.add(faExclamation);

// this one is the key to render the icon in the toast
dom.watch(); 

Vue.use(VueToasted, {
  iconPack: 'fontawesome',
});

this.$toasted.error('something bad happened', {
  icon: 'exclamation',
});
```

you'll probably want to also add this extra line of css
```
.toasted > svg:first-child {
  margin-right: .7rem;
}
```
