### ISSUE TITLE
Cannot show different messages in global toast

### ISSUE THREAD

**Issue by irvinlim** [shakee93/vue-toasted#45]
When I register a global toast like this:

```js
Vue.toasted.register('my_app_error', message => {
  return message || 'Oops.. Something Went Wrong..';
}, {
  type: 'error'
});
```

It works fine if I use this:

```js
this.$toasted.global.my_app_error("Hello");
```

However if I subsequently call the toast with a different message, the first message is displayed instead:

```js
this.$toasted.global.my_app_error("Bye Bye"); // Toast shows "Hello"
```

It seems like the message is being cached.

Repro JSFiddle link: https://jsfiddle.net/q7f0Lmf5/1/

**Comment by shakee93** [comment]
Thanks, i have tested, it is a bug in the new `register` method. you may use the legacy method while i fix this issue. [example here](https://github.com/shakee93/vue-toasted/blob/master/examples/reusable-toast.js)

**Comment by shakee93** [comment]
Nevermind, fixed it. please update to the latest version

**Comment by pjhartin** [comment]
Was this ever fixed? The same behaviour is still occurring for me

**Comment by shakee93** [comment]
yeah it is fixed. take a look at the repro fiddle.

**Comment by XanderLuciano** [comment]
Here's another way you could structure it if you needed more flexibility.

```javascript
Vue.use(Toasted);

Vue.toasted.register('test', payload => {
	if ( !Object.keys(payload).length ) 
  	return `Error Message`; // Empty object
  
  if ( !!payload.message )
  	return `object.message: ${ payload.message }`; // Custom object
  
  if ( typeof(payload) === 'string' )
  	return `String Passed: ${ payload }`; // string passed
}, 
'success');

new Vue({
  el: '#app',
  data: {
    message: 'Hello Vue.js!'
  },
  mounted() {
  	// payload == { message: '...' } so we need to use payload.message when registering
  	this.$toasted.global.test( {message: 'My Custom Message'} ); // Object Passed to function
  	this.$toasted.global.test( 'Just a string' ); // payload == 'just a string'
  	this.$toasted.global.test(); // Error Message
  }
});
```

https://jsfiddle.net/sa0k1jpg/
