### ISSUE TITLE
Showing toastr message after redirect

### ISSUE THREAD

**Issue by kashifullahwebdeveloper** [shakee93/vue-toasted#46]
Hi @shakee93, 

 Thank you for amazing plugin for vuejs. I have specific need and I am unable to do this using your plugin.
I want to show toastr message once I redirect a route using router-link in VueJs, Let's put this into an example, After user is created I want to redirect user to all users list and show toastr of success message, could you please guide me how can I achieve this. 

Thank you.

**Comment by shakee93** [comment]
vue router's push method has its second parameter as `onComplete` you can use this.
[check the router doc for `push` here](https://router.vuejs.org/en/api/router-instance.html#methods)

```javascript
this.$router.push('/to-my-users-list', () => {
   this.$toasted.show('Successfully Added User');
});
```

**Comment by kashifullahwebdeveloper** [comment]
That worked, thank you so much.

**Comment by wrabit** [comment]
Is there any solution if using next() from before each?

**Comment by shakee93** [comment]
you can use `Vue.toasted.show('hello')` to access outisde the component
