### ISSUE TITLE
Trigger onComplete event when goAway function is called

### ISSUE THREAD

**Issue by kljuco** [shakee93/vue-toasted#47]
In order do allow user to close toaster we want to add action for that. If we call `goAway ` function when action is clicked `onComplete ` is never fired, and we relay heavily on `onComplete` callback.
It would be great if this feature could be added.

**Comment by shakee93** [comment]
@kljuco sorry for the delayed response

what about passing a callback to `goAway` ?

**Comment by shakee93** [comment]
closing as no response

**Comment by ullalaaron** [comment]
Hi could we re-open this? I think there should be a way to pass onComplete function to close action. How would you do it?
