### ISSUE TITLE
Singleton Option: There's no delay between toasts.

### ISSUE THREAD

**Issue by bhansenmd** [shakee93/vue-toasted#48]
When I show multiple toasts in quick succession of each other with the singleton option set to true, the toasts quickly flash past leaving only the last one in the sequence. This makes it near impossible to read the messages all the toasts save the very last one.

I suggest that the toasts be displayed one by one. They would use the normal delay, fade away, and then after a configurable delay the next toast would be displayed.

**Comment by shakee93** [comment]
`singleton` is intended to do that.. it will be complicated to add such a feature.. 

if you disable the singleton, you can have the delay with the toasts.. or you can use the `onComplete` callback to achieve this behavior.
