### ISSUE TITLE
No link to pay shakee93 a coffee

### ISSUE THREAD

**Issue by paulogdm** [shakee93/vue-toasted#49]
This is unacceptable, how there is no link to pay you a cup of tea, coffee or a bear?

**Proposed solution**: Please add a BTC address or paypal for donations.

Thank you for this repo!

**Comment by shakee93** [comment]
Thanks buddy, really appreciate it, it means alot !!

i love developing and making this project better, with my spare time 😉  kinda my hobby.. and its a tiny project.. i think it already has what it deserves.. 😍
