### ISSUE TITLE
custom template

### ISSUE THREAD

**Issue by czytelny** [shakee93/vue-toasted#5]
Hi, I have 2 questions:
1. is there a option to setup custom template for toasts? for example when I call success message: `this.$toasted.success('Added succesfully')` I would like to add some icon from fontawesome... 
2. is there a option to add 'on-click' handler for toast to close it ?

**Comment by shakee93** [comment]
Hi there,

1. you can pass html to the message part `$toasted.success('<div>Added succesfully</div>')`. and you can also use the `className` option to set a class to the toast.

2. Yes of course you can. 

```javascript
let toast = this.$toasted.success('Added succesfully');

// toast.el contains the html element of the toast you may then set the listner
toast.el.addEventListener('click', () => {
     console.log('clicked');
})
```

Hope that helps..

**Comment by czytelny** [comment]
sweet, thank you! :)

**Comment by wett1988** [comment]
> Hi there,
> 
> 1. you can pass html to the message part `$toasted.success('<div>Added succesfully</div>')`. and you can also use the `className` option to set a class to the toast.
> 2. Yes of course you can.
> 
> ```js
> let toast = this.$toasted.success('Added succesfully');
> 
> // toast.el contains the html element of the toast you may then set the listner
> toast.el.addEventListener('click', () => {
>      console.log('clicked');
> })
> ```
> 
> Hope that helps..

Working code for use html element changed (`el` -> `$el`):

```javascript
toast.$el.addEventListener('click', () => {
  console.log('clicked');
})
```
