### ISSUE TITLE
Featured Request: Block UI

### ISSUE THREAD

**Issue by ibdf** [shakee93/vue-toasted#50]
Provide the option to block the rest of the UI when a notification has an action to prevent the user from clicking somewhere else why an action needs to be taken.

Right now this can be accomplished by adding a css class to the toasted container, and then styling that class to block everything else, but a simple boolean in options would be nice.

**Comment by shakee93** [comment]
do you have a working example of this feature?

**Comment by ibdf** [comment]
Only on localhost right now, so nope.

I am adding a class to

`containerClass: 'block-ui',`

```
.block-ui{
    &:before {
      content: "";
      position: absolute;
      top: -50%;
      left: -50%;
      width: 100000%;
      transform: translate(-50%,-50%);
      height: 100000%;
      overflow: hidden;
      background-color: rgba(grey,0.5);
      z-index: 0;
      transform: opacity 0.25s ease-in-out;
    }
  }
```

* I had to force  height and width because of the parent wrapper positioning, but this class could be a lot simpler, and/or it could be added to another container.

That prevents the user from being able to click anywhere else while the toasted message is showing.

**Comment by shakee93** [comment]
Great, looks promising ! is there any way we can animate the backdrop to fade away ? if we could do that we can implement this or will have to find another way to do this.

**Comment by shakee93** [comment]
sorry, closing as inactive
