### ISSUE TITLE
How to show two toasts with different layout options at the same time

### ISSUE THREAD

**Issue by rasikas** [shakee93/vue-toasted#51]
How to show two(or more) different toats with different UI settings (ex: container position) at the same time. Currently, if you show two toasts with different options both will inherit one set of options, 

ex: if you go to the [demo page](https://shakee93.github.io/vue-toasted/)  and set the duration to 1min and then click on 'Launch Toast' it will appear at the position you selected, now select different position and also select **full width** option **on**. and click on 'Launch Toast' you will see all the toasts (previously shown and the new one) will be full width and will also be moved to the new position. Ideally already shown toasts should keep there settings and positions regardless of the new toast settings.

This is very useful in asynchronous calls to back and show different messages to the UI.
It, however, retain the theme without affecting so I think you can make it work for other options (such as position and full-width) as well.

Use case:
we want to show action based toast at the center of the screen without full-width and other error and notifications at the bottom of the screen with full-width, but in current if a notification comes up while user action toast is visible, both will go to the bottom of the screen and will be full-width which is not user experience as suddenly it changes where user needs to click on.

**Comment by shakee93** [comment]
this behavior can be achieved via grouping. but unfortunately it's not available yet.. it will be available in the upcoming version.

you will be able to create multiple instances of toast containers. 

```javascript
let notificationToasts = this.$toasted.group({ /*...its options*/ })
notificationToasts.show('My Notification')
```

**Comment by rasikas** [comment]
Thanks, waiting for that

**Comment by shakee93** [comment]
group support is available now !
