### ISSUE TITLE
Request: Typescript types/definition files

### ISSUE THREAD

**Issue by sureshjoshi** [shakee93/vue-toasted#52]
This is a great library, that I'd love to use in my project, however, my project is entirely Typescript - and I'm still a bit of a TS noob, so I'm not entirely sure how to create TS definitions that also interact with the Vue plugin system.

I've tried some permutations, but each one falls over at some point - from compilation all the way to runtime.

I think right now, the biggest problem for me is that TS can't seem to pick up the this.$toasted variable, even though I'm following https://vuejs.org/v2/guide/typescript.html#Augmenting-Types-for-Use-with-Plugins and basically copied what Vue-Router did.

If there are any TS devs with more experience pulling 3rd party plugins in, I'd be happy to get something running and do a PR

**Comment by sureshjoshi** [comment]
Here's what I've tried so far, but it doesn't result in anything on the intellisense side, but at least it compiles (kinda). Keeping in mind I really don't know what I'm doing here, as there isn't as much info out as I'd have hoped.

In tsconfig.json:

    {
        "compilerOptions": {
            ...
            "typeRoots": [
                "@types",
                "./@types"
            ]


In project/src/@ types/vue-toasted/index.d.ts

    import "./vue";
    import { VueToasted } from "./toasted";
    export default VueToasted;


In project/src/@ types/vue-toasted/vue.d.ts

    import Vue from "vue";
    import VueToasted from "./index";

    declare module "vue/types/vue" {
        interface Vue {
            $toasted: VueToasted;
        }
    }
    // TODO: declare module "vue/types/options" {}

In project/src/@ types/vue-toasted/toasted.d.ts

    declare module "vue-toasted" {
        import Vue, { PluginFunction } from "vue";
        function install(): PluginFunction<any>;
        export interface VueToasted {
            show(message: string): void;
        }
    }

**Comment by Toilal** [comment]
I just wrote full definition files and opened a pull request, feel free to try those.

**Comment by sureshjoshi** [comment]
Thanks @Toilal 
I'll be back on this project in a day or two, so I'll test out your PR. It looks muuuuch better than the sloppy stuff I tried  :)

**Comment by shakee93** [comment]
thanks @Toilal i have merged that pull. will test it before the next version

**Comment by bizzzd** [comment]
Any chance to have it delivered to npm?

**Comment by sebstr1** [comment]
Took me a while before I understood that this was the problem. Does anyone know how I can fix this manually?

**Comment by gettinToasty** [comment]
Would love to see this released.

**Comment by shakee93** [comment]
Typescript support is released on npm with the latest version. closing this issue 🙌

**Comment by Karloski** [comment]
Sorry to pull up an old thread, but I think one of the definitions in your .d file is wrong. Currently you have:

register (name: string, message: string, options?: ToastOptions): void

However from what i can see it looks like register can support a function for the message parameter, so I think it should look something akin to:

register (name: string, message: string | Function, options?: ToastOptions): void

To prevent Typescript flagging it as an error.

Apologies if I have got this wrong and thanks for the great library :)
