### ISSUE TITLE
Don't show toastr when Session expires

### ISSUE THREAD

**Issue by kashifullahwebdeveloper** [shakee93/vue-toasted#53]
Hi @shakee93,

  I want to clear all previous toaster messages if session expires, for example, let's say the session expires and if user clicks on any link then User is redirected to Login page with toastr being shown with errors message, but I don't want to show that error toastr instead I am showing some other message, could you help me achieve this?

Thank you,

**Comment by shakee93** [comment]
@kashifullahwebdeveloper sorry for the delayed response. have you been able to resolve this issue ?

**Comment by kashifullahwebdeveloper** [comment]
@shakee93,

Thank you for reply, yes, I have.

**Comment by shakee93** [comment]
Great !! i am closing this issue. let me know if you need any assistance.

Thanks.
