### ISSUE TITLE
Compability with vue-fontawesome

### ISSUE THREAD

**Issue by pWnH** [shakee93/vue-toasted#57]
I am using the vue-fontawesome components for all the icons in my project, so is there a way to use this with it? 

The component looks like this:
`<font-awesome-icon :icon="['far', 'trash-alt']"></font-awesome-icon>`

[vue-fontawesome](https://www.npmjs.com/package/@fortawesome/vue-fontawesome)

**Comment by shakee93** [comment]
Hey the plugin actually works outside of Vue Scope. it works with vanilla javascript. if there is a way to compile this component and get the html output we will be able to implement this feature to the plugin

**Comment by shpfive** [comment]
Maybe you can provide a "custom" IconPack Option
My Solution:

 ```
case 'custom':
  var html = options.icon;
  var template = document.createElement('template');
  template.innerHTML = html;

  iel = template.content.firstChild;
  break;
```

then there is the possibility to use the fontawesome npm module to precompile the icons an pass it trough the toasted plugin

```title: 'HelloWorld',
        options: Object.assign({}, generalOptions,{
            theme:'primary',
            icon: {
                prefix: 'far',
                icon: 'exclamation-triangle'
            }
        })
```

and 

```
create: function(Vue) {
        Object.keys(toasts).forEach(function (toast,k) {
            toasts[toast].options.icon = compileVueFontawesome(toasts[toast].options.icon);
            Vue.toasted.register(toast, toasts[toast].title, toasts[toast].options)
        });
    },
```
```
const compileVueFontawesome = (Icon) => {
    return fontawesome.icon({ prefix: Icon.prefix , iconName: Icon.icon}).html
}
```

**Comment by pWnH** [comment]
@shpfive your solution works!
@shakee93 could we get this solution in the official release, so i dont have to maintain my own 'fix'-version? :)

**Comment by scriptcoded** [comment]
Any updates here?

**Comment by shakee93** [comment]
latest version supports to set a callback function as icon object. this can be used as the workaround for this issue. take a look at below example.

```javascript
Vue.use(VueToasted, {
	iconPack: 'callback'
});


Vue.toasted.show(
    'hello there, i am a toast !!', {
    // el is icon html element you can play with it
    icon: (el) => {
        el.innerText = 'my icon logic';
        return el;
    }
});
```

**Comment by libin-techversant** [comment]
I am using vue-fontawesome, but I am not clear about using it with vue-toasted.
In main.js
`let toastOptions ={
  position : 'top-right',
  duration: 4000,
  iconPack: 'callback'
}
Vue.use(Toasted, toastOptions)`

In mycomponent.vue
`this.$toasted.success(
          'Saved', 
          {
            icon : (el) => {
              el.innerText = `<font-awesome-icon icon="check" />`;
              return el;
            }
          }
 )`

**Comment by danielleford04** [comment]
Is it possible to get an example of this in the docs?  Like libin-techversant, I can't figure out what logic to pass in the callback to get this to work. 

Should it be the full font awesome component <font-awesome-icon>,
or a class name, or pure html?
It looks like it's just rendering an icon and inserting the <font-awesome-icon> as html (and not compiling it and showing the svg)

`    this.$toasted.show('Hello', {  
           type: "success",
           position: "bottom-right", 
           duration : 50000,
                icon : (el) => { el.innerHTML = '<font-awesome-icon icon="chart-pie"/>'; return el; } 
        });`

**Comment by hmmdeif** [comment]
It's because it hasn't been published to npm yet. You'll have to use the git repo directly if you want to use callback.

**Comment by danielleford04** [comment]
Thank you so much for clarifying and reassuring me I'm not completely incompetent! 

Do you guys have an estimated release date for when you'll get it on NPM?

**Comment by juljupy** [comment]
Hi, hope you all are doing well.

I was facing the same issue, I'm using vue-toasted v. 1.1.27 and I did this to make it work:

```
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import { library, dom } from '@fortawesome/fontawesome-svg-core'
import { faExclamationTriangle } from '@fortawesome/free-solid-svg-icons'
library.add(faExclamationTriangle)
dom.watch() // This was the line that did the trick
Vue.component('font-awesome-icon', FontAwesomeIcon)

// Then I use it this way
this.$toasted.show('Ocurrió un error',{
    type: 'error',
    icon : {
        name: 'fas fa-exclamation-triangle'
    }
})
```
Hope it helps!

**Comment by jerearaujo03** [comment]
> Hi, hope you all are doing well.
> 
> I was facing the same issue, I'm using vue-toasted v. 1.1.27 and I did this to make it work:
> 
> ```
> import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
> import { library, dom } from '@fortawesome/fontawesome-svg-core'
> import { faExclamationTriangle } from '@fortawesome/free-solid-svg-icons'
> library.add(faExclamationTriangle)
> dom.watch() // This was the line that did the trick
> Vue.component('font-awesome-icon', FontAwesomeIcon)
> 
> // Then I use it this way
> this.$toasted.show('Ocurrió un error',{
>     type: 'error',
>     icon : {
>         name: 'fas fa-exclamation-triangle'
>     }
> })
> ```
> 
> Hope it helps!

This worked for me!!
