### ISSUE TITLE
How to use multiple fontawesome classes for icon?

### ISSUE THREAD

**Issue by jakelumetta** [shakee93/vue-toasted#58]
I'd like to do this:  `icon : 'fa-spinner fa-spin',`  but it doesn't work.  Is it possible to have multiple classes for the icon option?

**Comment by Barterr** [comment]
I added a pull request for an icon with custom classes #65. Would make that which you're trying work.

**Comment by shakee93** [comment]
thanks to @giubatt with his PR you can achieve this. it is live in the latest version.
