### ISSUE TITLE
max toasts option

### ISSUE THREAD

**Issue by yuanyingfeiyu** [shakee93/vue-toasted#64]
Hi, I really like your work. But  I found max toast option in another vue toast project which is not available in your project. I really think this property is important, because without the number limit, the toasts will block the whole screen if the users toast in short time, which is not so friendly. I'd really appreciate that if you could add the max toasts option. Looking forward to your reply.

**Comment by FrancescoMussi** [comment]
Yes it could a nice option.
I am using the clear method to clear all previous instances before showing another toast. But it has a strange re-positioning of the toast. It goes down and up very fast. Not smooth.

**Comment by DimasInchidi** [comment]
+1 for option to set max stacked toast

**Comment by tranghaviet** [comment]
+1
It would be nice to replace `singleton` option with max toast to show

**Comment by shakee93** [comment]
PR welcome for this feature.
