### ISSUE TITLE
Is there a way to change the toast colors and button shapes?

### ISSUE THREAD

**Issue by sbasi5576** [shakee93/vue-toasted#66]
Thanks for creating this utility.  it is really good.  I am looking to change the colors but all the css seems to be minified.

**Comment by ManuLG** [comment]
You could register a custom toast and pass a classname as an option. In that class name you could set the background color:

```
    Vue.toasted.register('myToastName', function (message) {return message }, {
        type : 'info',
        duration: 3000,
        className: ['your-custom-class',]
    });
```

And in your css:

```
.your-custom-class {
    background-color: #ffffff !important; 
}
```

**Comment by shakee93** [comment]
thanks @ManuLG 🙌 closing this issue !

**Comment by deylyn** [comment]
> You could register a custom toast and pass a classname as an option. In that class name you could set the background color:
> 
> ```
>     Vue.toasted.register('myToastName', function (message) {return message }, {
>         type : 'info',
>         duration: 3000,
>         className: ['your-custom-class',]
>     });
> ```
> 
> And in your css:
> 
> ```
> .your-custom-class {
>     background-color: #ffffff !important; 
> }
> ```
esto no funciona

**Comment by devanflaherty** [comment]
This works for style but there doesn't seem to be a way to pass the options, if we wanted to add custom actions per toast on a custom registered toast.

**Comment by thechromosomes** [comment]
/* toast notification */
.v-toast__item--success{
  background-color: #c41e3a !important;
}
