### ISSUE TITLE
How to deal with icons that are added via "class"?

### ISSUE THREAD

**Issue by liuzhen2008** [shakee93/vue-toasted#68]
I am using Element UI as my UI components, and it already provides me with an icon solution.

however, i notice that when an icon is added.

Element UI differentiate icons based on the class.

`<i class="el-check-success"></i> `

This is how element UI renders an icon. Is this something compatible with toast icons? if it is, what API do I use to render the element UI icon? 

Thanks

**Comment by shakee93** [comment]
this is available in the latest version

take a look at the examples for 'custom-class'
https://github.com/shakee93/vue-toasted/blob/master/examples/using-icons.js
