### ISSUE TITLE
better push up animation?

### ISSUE THREAD

**Issue by zeroarst** [shakee93/vue-toasted#69]
I like this component, thanks for the effort.
The only think to make it perfect is the animation when stacking toast messages is not that good.
These two components have the same animation that looks more smooth.
https://github.com/ktsn/vuex-toast
http://astaroverov.github.io/#!/open-source/vue-toast

It would be good that it can also use the same animation..?

**Comment by shakee93** [comment]
the plugin uses animejs to create animations.

take a look at this file :
https://github.com/shakee93/vue-toasted/blob/master/src/js/animations.js

if you have a better animation. it is welcomed please submit a PR.

Thanks 🙌
