### ISSUE TITLE
material icon not working on my end

### ISSUE THREAD

**Issue by setsunashou14** [shakee93/vue-toasted#73]
![image](https://user-images.githubusercontent.com/40367781/41554075-5593224a-7366-11e8-9341-4d238ad7ca25.png)

As you can see, it's not working on my end.
My code is like this:
```
import Vue from 'vue'
import Toasted from 'vue-toasted';
Vue.use( Toasted)

Vue.toasted.show('hello there, i am a toast !!', { icon : 'check'});
```
Do I need to install first the material icons lib then import it?

**Comment by patskot** [comment]
I had the same problem and you are correct, you need to install and import the material icons library.

`npm install material-icons --save`

Then you can include it via: 
```
import '../node_modules/material-icons/iconfont/material-icons.scss
```

or, I put mine in my main.scss like so:
```
$material-icons-font-path: '~material-icons/iconfont/';
@import '~material-icons/iconfont/material-icons.scss';
```

**Comment by cjlaborde** [comment]
If you use Nuxt.js add to nuxt.config.js
```js
 css: ["@/node_modules/material-design-icons/iconfont/material-icons.css"],
 ```
