### ISSUE TITLE
Problems with how the class (.error, .info and .success) css is added in toast

### ISSUE THREAD

**Issue by jeftarmascarenhas** [shakee93/vue-toasted#77]
I'm trying a problem with the class css .info, .success and .erro by the way it's implemented in javascript.

If the first toast is of type error all other toast that come after the toast of the error type are left with the appearance of the error because the class .error continues in the next toast created.

### Problem
![print-screen-toasted](https://user-images.githubusercontent.com/574887/42597364-d79e8ad4-852e-11e8-8a59-63b8f01704d1.PNG)

### Cause of problem
![print-screen-toasted-code](https://user-images.githubusercontent.com/574887/42597374-de6b647c-852e-11e8-9f5f-f4bb40781da5.PNG)

**Comment by shakee93** [comment]
this is fixed in the latest version !!

**Comment by xming13** [comment]
@shakee93 I have the same issue on version 1.1.27 and 1.1.28
