### ISSUE TITLE
Default icons for each type of toaster

### ISSUE THREAD

**Issue by robsontenorio** [shakee93/vue-toasted#78]
All "success" tosters has the same icon on entire app!
```
this.$toast.success('All right!', {
    icon: 'check'
})
```

Is it possible to set default icons (on global config) to each type of toaster?

Something like this
```
toast: {
    duration: 5000,
    className: 'application',
    position: 'bottom-right',
    icons: {
        success: 'check',
         ...
    }
  },
```

It would be very nice, just do this, and icon will be there ;)
```
this.$toast.success('All right!')
```

**Comment by shakee93** [comment]
you can easily achieve this via custom toast registration. take a look at the documentation : https://github.com/shakee93/vue-toasted#custom-toast-registration

**Comment by robsontenorio** [comment]
Yes, indeed. But i am considering to submit a PR like described above: optional way to set default icons globaly, with no need of “custom toast registration”. Will you consider it? 

—
Robson Tenório

Em 13 de jul de 2018, à(s) 07:33, Shakeeb Sadikeen <notifications@github.com> escreveu:

**Comment by shakee93** [comment]
lol it's too late from me, PR is welcome 🙌
