### ISSUE TITLE
SSR not compatible?

### ISSUE THREAD

**Issue by 5hanth** [shakee93/vue-toasted#79]
running into  [this issue](https://medium.com/@codebeast_/why-your-third-party-plugin-dont-work-in-nuxt-and-how-to-fix-it-d1a8caadf422)

`window is not defined` on server rendering.

Suggested solutions in medium post didn't help. 

any ideas?

**Comment by shakee93** [comment]
take a look at #11. you should exclude `vue-toasted` from SSR
