### ISSUE TITLE
Feature request: global toast handler

### ISSUE THREAD

**Issue by christianmalek** [shakee93/vue-toasted#8]
Hi,

I really like your project!

At the moment I'm implementing error messages in a web application. The problem is that sometimes the errors have specific properties I want to "toast" and sometimes I just want to print out a generic error message.

I could treat every single error. But this would result in repetitive code. What I really need is something like an function which would be called after invoking a new toast:
```js
function handleError(error) {
  if (error.specificProperty) {
    return error.specificProperty
  }
  return "An error occured."
}
```

It would be neat If I could pass a function like this to the options object of *vue-toasted* and every toast (or just errors) could be handled with this function.

**Comment by shakee93** [comment]
i have added this feature. update your plugin to the latest version (1.0.26)

```javascript
Vue.use(Toasted, {
    globalToasts : {
        appError : function(payload, inititate){

           // your logic here 
           if(payload.yourProperty) {
                 return inititate("Another Message", 'error');
           }

           return inititate("An error occured", 'error');
        },
        // another one
    }
});
```

you may use it in the component as 

```javascript
this.$toasted.global.appError({
    yourProperty: true
});
```

hope that helps 😉

**Comment by christianmalek** [comment]
@shakee93 You're awesome! I'll test it tomorrow and give you feedback. Thank you very much!

**Comment by christianmalek** [comment]
@shakee93 Works like a charm.
