### ISSUE TITLE
Could not use typescipt declare

### ISSUE THREAD

**Issue by duylddev** [shakee93/vue-toasted#81]
I saw typescript declare file in types/index.d.ts
But when i install. That's all i fetched:
![image](https://user-images.githubusercontent.com/9783862/44846475-a17b4c80-ac7a-11e8-84b0-b503d18f08cf.png)
Version is 1.1.24
![image](https://user-images.githubusercontent.com/9783862/44846566-e69f7e80-ac7a-11e8-8598-d8904b436e0f.png)
Obviously, i can't use typescript with those files.
what should i do?

**Comment by viktor-ku** [comment]
Yeah, the same

**Comment by viktor-ku** [comment]
https://github.com/shakee93/vue-toasted/pull/84

**Comment by shakee93** [comment]
this should be fixed in the latest release if not please reopen the issue. thanks 🙌
