### ISSUE TITLE
Class name conflict with vuetify

### ISSUE THREAD

**Issue by VladimirBulanov** [shakee93/vue-toasted#83]
Hi! 

I'm using vuetify in my project, and class name "primary" in toast div conflicts with default vuetify theme (because there're some styles with !important tag in vuetify theme). This leads to unavailability to completely style the toast using custom css-classes. 

My suggestion is to change the class name of generating div with toast to something like "toasted-primary", so it wouldn't conflict with the class names in other libraries, class name "primary" is too generic, imo. 

Thanks in advance!

**Comment by knackjason** [comment]
A naming convention like BEM would definitely help and make the styles very clear.
