### ISSUE TITLE
Typescript declaration not fully typed

### ISSUE THREAD

**Issue by phu54321** [shakee93/vue-toasted#90]
Trying to use vue-toasted in typescript yields this error.

```
ERROR in /Users/whyask37/gitclones/kian/node_modules/vue-toasted/types/index.d.ts
46:14 Parameter 'e' implicitly has an 'any' type.
    44 |    * @returns {any}
    45 |    */
  > 46 |   onClick?: (e, toastObject: ToastObject) => any
       |              ^
    47 | }
    48 |
    49 | interface ToastOptions {
ERROR in /Users/whyask37/gitclones/kian/node_modules/vue-toasted/types/index.d.ts
147:3 'register', which lacks return-type annotation, implicitly has an 'any' return type.
    145 |    * @param options
    146 |    */
  > 147 |   register (name: string, message: string, options?: ToastOptions)
        |   ^
    148 |
    149 |   /**
    150 |    * Clear all toasts
ERROR in /Users/whyask37/gitclones/kian/node_modules/vue-toasted/types/index.d.ts
152:3 'clear', which lacks return-type annotation, implicitly has an 'any' return type.
    150 |    * Clear all toasts
    151 |    */
  > 152 |   clear ()
        |   ^
    153 | }
    154 |
    155 | declare module 'vue/types/vue' {
```

I could ignore this errors if I want to, but I think this needs some fix from package-side.

**Comment by LuckyURE** [comment]
@phu54321 I agree that the author should fix the TS issues (or at least someone with a few minutes to do a PR could).. but this problem can be solved by adding the following to your tsconfig.json:

"skipLibCheck": true

**Comment by Erzed** [comment]
Hello, why interfaces in typings ( `ToastedPlugin`, `Toasted` etc) doesn't exported?

**Comment by qw3ry** [comment]
I found an additional type issue:
When registering a toast and trying to execute it, the typescript compiler fails at `this.$toasted.global.myToast()` because `global` is unknown to typescript.
`(this.$toasted as any).global.myToast()` succeeds
