### ISSUE TITLE
Can't use plugin in vue-cli project

### ISSUE THREAD

**Issue by byrnedo** [shakee93/vue-toasted#95]
Made a new project using vue-cli and typescript. 

Getting the following when trying it `use` vue-toasted:

```
Argument of type 'typeof import("/.../node_modules/vue-toasted/types/index")' is not assignable to parameter of type 'PluginObject<any> | PluginFunction<any>'.
  Type 'typeof import("/.../node_modules/vue-toasted/types/index")' is not assignable to type 'PluginFunction<any>'.
    Type 'typeof import("/.../node_modules/vue-toasted/types/index")' provides no match for the signature '(Vue: VueConstructor<Vue>, options?: any): void'. [2345]
```

**Comment by byrnedo** [comment]
I see the types file has been updated but isn't in the latest published version.

**Comment by shakee93** [comment]
types has been published with the latest version

**Comment by shrik15** [comment]
Not able to use Toasted in my vue project. Getting an error "export 'default' (imported as 'Toasted') was not found in 'vue-toasted'
