### ISSUE TITLE
Inconsistent CSS declarations

### ISSUE THREAD

**Issue by jbussemaker** [shakee93/vue-toasted#98]
It seems that the CSS declarations made by vue-toasted.min.css and vue-toasted.js are not compatible, leading to the wrong CSS being included in the Vue app if used like this:

```javascript
import Toasted from 'vue-toasted';
Vue.use(Toasted);
```

If used like this it works for now:

```javascript
import Toasted from 'vue-toasted';
Vue.use(Toasted);

import 'vue-toasted/dist/vue-toasted.min.css';
````

The solution is unintuitive though, so it would be nice if this could be fixed.

**Comment by shakee93** [comment]
this is being fixed in the latest version
